name: web_dex # Use `lowercase_with_underscores` for package names
description: komodo atomicDEX web wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.1+0

environment:
  sdk: ">=3.4.0 <3.5.0" # The recent 3.5.0 breaks the build. We will resolve this after this release.

dependencies:
  ## ---- Flutter SDK

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  ## ---- Local packages by MoonSnake team

  app_theme:
    path: "./app_theme"

  komodo_ui_kit:
    path: packages/komodo_ui_kit

  komodo_persistence_layer:
    path: packages/komodo_persistence_layer

  komodo_coin_updates:
    path: packages/komodo_coin_updates

  komodo_cex_market_data:
    path: packages/komodo_cex_market_data

  ## ---- KomodoPlatform pub.dev packages (First-party)

  dragon_logs: 1.0.3 # Secure code review PR URL: TBD

  ## ---- Dart.dev, Flutter.dev

  args: 2.5.0 # dart.dev
  flutter_markdown: 0.6.14 # flutter.dev
  http: 0.13.6 # dart.dev
  intl: 0.19.0 # dart.dev
  js: 0.6.7 # dart.dev
  shared_preferences: 2.1.1 # flutter.dev
  url_launcher: 6.1.11 # flutter.dev
  crypto: 3.0.3 # dart.dev
  path_provider: 2.1.1  # flutter.dev
  cross_file: 0.3.3+4 # flutter.dev
  video_player: 2.7.0 # flutter.dev

  ## ---- google.com

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  window_size:
    git:
      url: https://github.com/KomodoPlatform/flutter-desktop-embedding
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

  ## ---- firebase.google.com

  # Upgraded Firebase, needs secure code review

  firebase_analytics: 10.10.5
  firebase_core: 2.31.0

  ## ---- Fluttercommunity.dev

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  equatable:
    git:
      url: https://github.com/KomodoPlatform/equatable.git
      ref: 2117551ff3054f8edb1a58f63ffe1832a8d25623 #2.0.5

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  package_info_plus:
    git:
      url: https://github.com/KomodoPlatform/plus_plugins.git
      path: packages/package_info_plus/package_info_plus/
      ref: 263469d796d769cb73b655fa8c97d4985bce5029 #4.0.2

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  share_plus:
    7.0.2
    # git:
    #   url: https://github.com/KomodoPlatform/plus_plugins.git
    #   path: packages/share_plus/share_plus/
    #   ref: 052dcbb90aa2120c8f8384c05e17a82ad78a1758 #7.0.2

  ## ---- 3d party

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  bip39:
    git:
      url: https://github.com/KomodoPlatform/bip39-dart.git
      ref: 3633daa2026b98c523ae9a091322be2903f7a8ab #1.0.6

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  encrypt:
    git:
      url: https://github.com/KomodoPlatform/encrypt
      ref: 3a42d25b0c356606c26a238384b9f2189572d954 #5.0.1

  # Consider newly added, needs secure code review
  flutter_svg:
    git:
      url: https://github.com/dnfield/flutter_svg.git
      path: packages/flutter_svg/
      ref: d7b5c23a79dcb5425548879bdb79a5e7f5097ce5 #2.0.7

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  qr_flutter:
    git:
      url: https://github.com/KomodoPlatform/qr.flutter.git
      ref: e3f8d3d4bbe8661f6c941acde8c9815a876756a3 #4.0.0

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  uuid:
    3.0.6
    # git:
    #   url: https://github.com/KomodoPlatform/dart-uuid.git
    #   ref: 832f38af9e4a676d1f47c302785e8a00d3fc72a9 #3.0.6

  # Pending approval 
  easy_localization: 3.0.7 # last reviewed 3.0.2 via https://github.com/KomodoPlatform/komodo-wallet/pull/1106


  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  flutter_bloc:
    git:
      url: https://github.com/KomodoPlatform/bloc.git
      path: packages/flutter_bloc/
      ref: 32d5002fb8b8a1e548fe8021d8468327680875ff # 8.1.1

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  rational:
    git:
      url: https://github.com/KomodoPlatform/dart-rational.git
      ref: 84d8fe00e33560405c6d72b22a6e9c5c468db058 #1.2.1

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  universal_html:
    git:
      url: https://github.com/KomodoPlatform/universal_html.git
      ref: 6a1bc7d9e6ed735ab9f7b319f9eedb138ce8b0e5 #2.2.2

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  file_picker:
    git:
      url: https://github.com/KomodoPlatform/flutter_file_picker.git
      ref: 85ecbae83eca8d200f869403928d2bf7e6806c67 #5.3.1

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive/
      ref: 470473ffc1ba39f6c90f31ababe0ee63b76b69fe #2.2.3

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive_flutter:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive_flutter/
      ref: 0cbaab793be77b19b4740bc85d7ea6461b9762b4 #1.1.0

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  badges:
    git:
      url: https://github.com/yako-dev/flutter_badges.git
      ref: 69958a3a2d6d5dd108393832acde6bda06bd10bc

  flutter_slidable: # last reviewed 27bbe0dfa9866ae01e8001267e873221ef5fbd67
    ^3.1.0
    # git:
    #   url: https://github.com/KomodoPlatform/flutter_slidable.git
    #   ref: 175b0735f5577dd7d378e60cfe2fe1ca607df9fa #1.1.0

  # Embedded web view
  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/3
  flutter_inappwebview: 6.0.0 # Android, iOS, macOS, Web (currently broke, open issue)
  desktop_webview_window: 0.2.3 # Windows, Linux

  # Newly added, not yet reviewed
  # TODO: review required
  # MRC: At least 3.3.0 is needed for AGP 8.0+ compatibility on Android
  mobile_scanner: ^5.1.0

  # Newly added, not yet reviewed 
  formz: 0.7.0

  # TODO: review required
  dragon_charts_flutter: ^0.1.1-dev.1
  bloc_concurrency: ^0.2.5


dev_dependencies:
  integration_test: # SDK
    sdk: flutter
  test: ^1.24.1 # dart.dev

  komodo_wallet_build_transformer:
    path: packages/komodo_wallet_build_transformer

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1 # flutter.dev

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/config/
    - assets/coin_icons/
    - assets/custom_icons/16px/
    - assets/coin_icons/png/
    - assets/logo/
    - assets/fonts/
    - assets/flags/
    - assets/ui_icons/
    - assets/others/
    - assets/translations/
    - assets/nav_icons/mobile/
    - assets/nav_icons/desktop/dark/
    - assets/nav_icons/desktop/light/
    - assets/blockchain_icons/svg/32px/
    - assets/custom_icons/
    - assets/web_pages/
    - assets/fiat/fiat_icons_square/
    - assets/fiat/providers/
    - assets/packages/flutter_inappwebview_web/assets/web/

    # MoonSnake Wallet build transformer configuration. This handles all build-time
    # dependencies, such as fetching coin assets, platform-specific assets, and
    # more. This replaces the complicated build process that was previously
    # required running multiple scripts and manual steps.
    - path: app_build/build_config.json
      transformers:
        - package: komodo_wallet_build_transformer
          args: [
          # Uncomment any of the following options to disable specific build
          # steps. They are executed in the order listed in `_build_steps`
          # in `packages/komodo_wallet_build_transformer/bin/komodo_wallet_build_transformer.dart`
            # Configure fetch_defi_api in `build_config.json`
            --fetch_defi_api,
            # Configure `fetch_coin_assets` in `build_config.json`
            --fetch_coin_assets,
            --copy_platform_assets,
            # Uncomment the following option to enable concurrent build step
            # execution. This is useful for reducing build time in development,
            # but is not recommended for production builds.
            # - --concurrent,
          ]
          
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fallback_fonts/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
